# Generated by Django 4.2.7 on 2023-11-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=36, verbose_name='uid')),
                ('tag', models.CharField(max_length=50, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.DateTimeField(blank=True, null=True)),
                ('uid', models.CharField(max_length=36, verbose_name='uid')),
                ('fc_imp_chk', models.IntegerField()),
                ('fc_time_chk', models.IntegerField()),
                ('utmtr', models.IntegerField()),
                ('mm_dma', models.IntegerField()),
                ('osName', models.CharField(max_length=50, verbose_name='osName')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('hardware', models.CharField(max_length=50, verbose_name='hardware')),
                ('site_id', models.CharField(max_length=100, verbose_name='site_id')),
            ],
        ),
    ]
