# Generated by Django 4.2.7 on 2023-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.CharField(db_index=True, max_length=50, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uid',
            field=models.CharField(db_index=True, max_length=36, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='view',
            name='mm_dma',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='reg_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='site_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='site_id'),
        ),
        migrations.AlterField(
            model_name='view',
            name='uid',
            field=models.CharField(db_index=True, max_length=36, verbose_name='uid'),
        ),
    ]
